### ISSUE TITLE
Проблема с бэкендом

### ISSUE THREAD

**Issue by Rubicones** [amstiel/bltpsk-hw#1]
Привет! Проверяю твой проект. У меня почему-то возникла проблема с запуском проекта, он не хочет подтягивать данных с бэка, хотя сервер запущен и лежит по порту 3001. Может у тебя слушает не тот порт? Проверь пожалуйста, пока не ставлю оценку, думаю разберемся :)
<img width="526" alt="image" src="https://github.com/amstiel/bltpsk-hw/assets/47296948/05664f2d-25dc-4052-acf5-81aa03fafe6a">
<img width="748" alt="image" src="https://github.com/amstiel/bltpsk-hw/assets/47296948/cc095f41-9992-4979-afd3-756d5cb70fd8">

**Comment by amstiel** [comment]
@Rubicones А у тебя в `.env` прописал url до сервера? Я не хардкодил url и порт, вынес в переменные окружения.

<img width="614" alt="image" src="https://github.com/amstiel/bltpsk-hw/assets/9428948/41c2961d-d271-4747-93eb-b05e27694379">

Ну и плюс я демо залил на https://bltpsk-hw.vercel.app/ (Первая загрузка данных может быть долгая чуть-чуть, потому что бэкенд иногда уходит спать и его надо "будить" первым запросом. Зато потом всё быстро должно быть.)

**Comment by Rubicones** [comment]
От редактирования env ничего не поменялось, но проверил по ссылке :) 
Получилось 10 баллов, -0.33 балла за пункт 4.3 потому что модалка не открывается, когда нажиммаешь минус при одном билете, -0.5 за 9.1, у модалки нет ховеров и -0.25 за 1.3, у фильтров нет значения "не выбран", поэтому отменить их никак нельзя. 
Как-то так!)

**Comment by amstiel** [comment]
Ну фильтры можно отменить при нажатии снова на тот же пункт в селекте, кстати. Явного поведения не было описано)

А hover на кнопках в модалке и правда забыл сделать.
